dist: focal
sudo: required
services:
  - docker

before_install:
  - docker build -t mandarteli/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mandarteli/complex-test npm test

after_success:
  - docker build -t mandarteli/multi-client ./client
  - docker build -t mandarteli/multi-nginx ./nginx
  - docker build -t mandarteli/multi-server ./server
  - docker build -t mandarteli/multi-worker ./worker